import type { Quest } from '../gameTypes.tutorial';

export const STARTER_QUESTS: Quest[] = [
  {
    id: 'quest_first_generator',
    title: 'Первый источник энергии',
    description: 'Постройте Генератор Mk1 для производства энергии',
    type: 'build',
    target: 'generator_mk1',
    targetAmount: 1,
    currentAmount: 0,
    reward: {
      credits: 500,
      researchPoints: 50,
    },
    isCompleted: false,
    isActive: true,
  },
  {
    id: 'quest_coal_mine',
    title: 'Добыча ресурсов',
    description: 'Постройте Угольную шахту для добычи угля',
    type: 'build',
    target: 'coal_mine',
    targetAmount: 1,
    currentAmount: 0,
    reward: {
      credits: 300,
      researchPoints: 30,
    },
    isCompleted: false,
    isActive: true,
  },
  {
    id: 'quest_research_lab',
    title: 'Наука - сила!',
    description: 'Постройте Исследовательский центр',
    type: 'build',
    target: 'research_center',
    targetAmount: 1,
    currentAmount: 0,
    reward: {
      credits: 1000,
      researchPoints: 200,
    },
    isCompleted: false,
    isActive: true,
  },
  {
    id: 'quest_first_tech',
    title: 'Первое открытие',
    description: 'Исследуйте любую технологию',
    type: 'research',
    target: 'any',
    targetAmount: 1,
    currentAmount: 0,
    reward: {
      credits: 2000,
      influence: 10,
    },
    isCompleted: false,
    isActive: true,
  },
  {
    id: 'quest_ten_buildings',
    title: 'Промышленная база',
    description: 'Постройте 10 зданий',
    type: 'build',
    target: 'any',
    targetAmount: 10,
    currentAmount: 0,
    reward: {
      credits: 5000,
      researchPoints: 500,
      influence: 25,
    },
    isCompleted: false,
    isActive: true,
  },
  {
    id: 'quest_sell_resources',
    title: 'Торговец',
    description: 'Продайте ресурсы на рынке',
    type: 'produce',
    target: 'market_sale',
    targetAmount: 1,
    currentAmount: 0,
    reward: {
      credits: 1500,
    },
    isCompleted: false,
    isActive: true,
  },
  {
    id: 'quest_unlock_galaxy',
    title: 'За пределы дома',
    description: 'Откройте вторую галактику',
    type: 'explore',
    target: 'gas_giants',
    targetAmount: 1,
    currentAmount: 0,
    reward: {
      credits: 10000,
      researchPoints: 1000,
      influence: 50,
    },
    isCompleted: false,
    isActive: true,
  },
  {
    id: 'quest_build_platform',
    title: 'Космический форпост',
    description: 'Постройте платформу в любой галактике',
    type: 'build',
    target: 'platform',
    targetAmount: 1,
    currentAmount: 0,
    reward: {
      credits: 15000,
      influence: 100,
    },
    isCompleted: false,
    isActive: true,
  },
  {
    id: 'quest_first_ship',
    title: 'Флот начинается',
    description: 'Постройте первый корабль',
    type: 'build',
    target: 'ship',
    targetAmount: 1,
    currentAmount: 0,
    reward: {
      credits: 20000,
      influence: 150,
    },
    isCompleted: false,
    isActive: true,
  },
  {
    id: 'quest_defeat_enemy',
    title: 'Первая кровь',
    description: 'Уничтожьте врага',
    type: 'combat',
    target: 'enemy',
    targetAmount: 1,
    currentAmount: 0,
    reward: {
      credits: 10000,
      researchPoints: 500,
      influence: 100,
    },
    isCompleted: false,
    isActive: true,
  },
];
