import { P } from './svgKit';

/**
 * Maps every emoji the game data still stores to a glyph from the futuristic
 * icon set. The emoji strings stay in the data files as stable identifiers —
 * only the *rendering* changed, so nothing about balance or saves moves.
 *
 * A value is either a glyph id, or a glyph id plus a colour override (used for
 * the coloured status dots, which share one hex-node glyph).
 */
export type EmojiEntry = string | { g: string; a: string; b: string };

const dot = (a: string, b: string) => ({ g: 'node', a, b });

export const EMOJI_GLYPH: Record<string, EmojiEntry> = {
  /* ---------------------------------------------------------------- energy */
  '⚡': 'bolt',
  '🔋': 'battery',
  '☀': 'solar',
  '☢': 'radiation',
  '⚛': 'atom',
  '🔥': 'flame',
  '🔌': 'plug',
  '⛽': 'fuel',
  '🛢': 'oil',
  '💨': 'gas',
  '🌫': 'gas',
  '🫠': 'droplet',

  /* ------------------------------------------------------------- materials */
  '🪨': 'ore',
  '⛏': 'drill',
  '❄': 'ice',
  '🧊': 'ice',
  '🌿': 'leaf',
  '🌱': 'leaf',
  '🌳': 'leaf',
  '🔩': 'nut',
  '🔧': 'wrench',
  '⚙': 'gear',
  '🪟': 'glassPane',
  '🧪': 'chemicals',
  '⚗': 'chemicals',
  '🧵': 'fiber',
  '🏖': 'sand',
  '🏜': 'desert',
  '♻': 'recycle',
  '🗑': 'waste',
  '📦': 'crate',

  /* ----------------------------------------------------------- electronics */
  '💾': 'wafer',
  '💻': 'cpu',
  '🖥': 'cpu',
  '📺': 'display',
  '📡': 'radar',
  '🧬': 'dna',
  '🦾': 'cyberarm',
  '🧠': 'brain',
  '🤖': 'robot',

  /* -------------------------------------------------------------- industry */
  '🏭': 'factory',
  '🏗': 'crane',
  '🏠': 'home',
  '🏢': 'city',
  '🌆': 'city',
  '🗼': 'tower',
  '🏛': 'temple',
  '🏰': 'castle',
  '🏪': 'market',
  '🏦': 'bank',
  '🏟': 'stadium',
  '🎡': 'ferris',
  '🏕': 'tent',
  '🗿': 'statue',
  '🗽': 'statue',
  '🌋': 'volcano',

  /* -------------------------------------------------------------- military */
  '🛡': 'shield',
  '🎯': 'turret',
  '⚔': 'swords',
  '🗡': 'swords',
  '🔫': 'weapon',
  '💣': 'bomb',
  '💥': 'blast',
  '🚨': 'siren',
  '🆘': 'siren',

  /* ----------------------------------------------------------------- space */
  '🚀': 'rocket',
  '🛰': 'satellite',
  '🛸': 'ufo',
  '🌌': 'galaxy',
  '🌀': 'vortex',
  '🕳': 'blackhole',
  '☄': 'comet',
  '🌠': 'comet',
  '🌑': 'moon',
  '🌍': 'globe',
  '🌐': 'globe',
  '✨': 'sparkle',
  '💫': 'sparkle',
  '🌟': 'starburst',
  '⭐': 'starburst',
  '🎉': 'starburst',

  /* ------------------------------------------------------------- creatures */
  '👾': 'bug',
  '🦟': 'swarm',
  '🦠': 'virus',
  '☠': 'skull',
  '💀': 'skull',
  '👹': 'demon',
  '💢': 'demon',
  '👁': 'eye',
  '🏴': 'skull',
  '👑': 'crown',
  '👤': 'person',
  '🐂': 'bull',
  '🐻': 'bear',
  '🐋': 'whale',

  /* --------------------------------------------------------------- economy */
  '💰': 'credits',
  '💵': 'cash',
  '💳': 'card',
  '💎': 'gem',
  '💹': 'chartUp',
  '📈': 'chartUp',
  '📉': 'chartDown',
  '📊': 'chartBars',
  '💱': 'exchange',
  '⚖': 'scale',
  '💼': 'briefcase',
  '🧾': 'receipt',
  '💸': 'moneyFly',
  '💯': 'hundred',
  '₿': 'crypto',
  Ω: 'omega',
  '🛒': 'cart',
  '🤝': 'handshake',
  '🏷': 'tag',

  /* ------------------------------------------------------------- logistics */
  '🚛': 'truck',
  '🚚': 'truck',
  '📥': 'import',
  '📤': 'export',
  '📂': 'folder',
  '🗄': 'archive',
  '🔗': 'link',
  '🧭': 'compass',
  '🗺': 'map',
  '📍': 'pin',

  /* ------------------------------------------------------------- knowledge */
  '🔬': 'research',
  '🔭': 'telescope',
  '🔍': 'search',
  '💡': 'bulb',
  '📚': 'book',
  '📖': 'book',
  '📜': 'scroll',
  '📰': 'news',
  '📋': 'clipboard',
  '📝': 'clipboard',
  '📐': 'ruler',
  '🔢': 'numbers',
  '🎓': 'graduate',
  '🔮': 'crystalBall',

  /* --------------------------------------------------------------- culture */
  '🎨': 'palette',
  '🎭': 'mask',
  '🎵': 'music',
  '🎼': 'music',
  '🎬': 'film',
  '🎮': 'gamepad',
  '🕹': 'gamepad',
  '👗': 'garment',
  '🎩': 'garment',
  '👓': 'glasses',
  '🥽': 'vr',
  '🏆': 'trophy',
  '🥇': 'medal',
  '🥈': 'medal',
  '🥉': 'medal',
  '🎁': 'gift',
  '❤': 'heart',
  '☮': 'peace',
  '🍀': 'clover',
  '⚜': 'fleur',
  '♾': 'infinity',

  /* ---------------------------------------------------------------- health */
  '💊': 'pill',
  '💉': 'syringe',
  '🧴': 'bottle',
  '🗜': 'clamp',

  /* -------------------------------------------------------------- comms/ui */
  '📱': 'phone',
  '💬': 'chat',
  '☁': 'cloud',
  '🔒': 'lock',
  '🔐': 'lock',
  '🔓': 'unlock',
  '⏳': 'hourglass',
  '⏰': 'clock',
  '🕐': 'clock',
  '📅': 'calendar',
  '🔄': 'refresh',
  '↻': 'refresh',
  '💤': 'sleep',

  /* ---------------------------------------------------------------- status */
  '✅': 'check',
  '✓': 'check',
  '❌': 'cross',
  '✗': 'cross',
  '✕': 'cross',
  '⚠': 'warning',
  '🚫': 'ban',
  '🛑': 'stop',
  '❓': 'question',
  '⏸': 'pause',
  '▶': 'play',
  '⏩': 'fastForward',
  '😊': 'faceHappy',
  '😄': 'faceHappy',
  '🙂': 'faceHappy',
  '😐': 'faceNeutral',
  '😕': 'faceNeutral',
  '😢': 'faceSad',

  /* ------------------------------------------------------------- direction */
  '→': 'arrowRight',
  '➡': 'arrowRight',
  '👉': 'arrowRight',
  '←': 'arrowLeft',
  '↑': 'arrowUp',
  '⬆': 'arrowUp',
  '↓': 'arrowDown',
  '▲': 'triangleUp',
  '▼': 'triangleDown',
  '➕': 'plus',

  /* --------------------------------------------- coloured status indicators */
  '🟢': dot(P.mint, P.mintDeep),
  '🔴': dot(P.rose, P.roseDeep),
  '🟡': dot(P.gold, P.goldDeep),
  '🟠': dot(P.amber, P.amberDeep),
  '🔵': dot(P.azure, P.azureDeep),
  '🔹': dot(P.azure, P.azureDeep),
  '🔷': dot(P.azure, P.azureDeep),
  '🔶': dot(P.amber, P.amberDeep),
  '⚪': dot(P.steel, P.steelDeep),
  '⚫': dot(P.inkDeep, P.ink),
  '⬜': dot(P.steel, P.steelDeep),
  '⬡': 'hex',
  '○': 'hex',
};

/**
 * Semantic aliases so new code can ask for an icon by name instead of pasting
 * an emoji: <GameIcon icon="energy" />.
 */
export const NAMED_GLYPH: Record<string, string> = {
  energy: 'bolt',
  ore: 'ore',
  ice: 'ice',
  carbon: 'leaf',
  steel: 'ingot',
  dark_matter: 'galaxy',
  research: 'research',
  credits: 'credits',
  building: 'factory',
  warehouse: 'crate',
  power: 'bolt',
  pollution: 'waste',
  combat: 'swords',
  fleet: 'rocket',
  prestige: 'starburst',
  quest: 'quest',
  market: 'market',
  settings: 'gear',
  help: 'question',
};
